### ISSUE TITLE
README - join up with dfeR::create_project() and update to be .md files

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/analysts-guide#108]
Currently at https://dfe-analytical-services.github.io/analysts-guide/RAP/rap-statistics.html#writing-a-readme-file, we have this: 

![image](https://github.com/user-attachments/assets/af3a559d-996d-440e-aca4-05cd658f5db2)

We should update it a bit as it's not strictly accurate anymore:

- [ ] Switch .txt to .md, and point to some basic markdown guidance as well. Explain / show how .md render nicely in Azure DevOps / GitHub etc
- [ ] Point to the `dfeR::create_project()` function for how to get started
- [ ] Join up with with the [dfeR function](https://github.com/dfe-analytical-services/dfeR/blob/main/R/create_project.R) / dfeR package more widely so there is a template readme and link to that

**Comment by Lsnaathorst1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [README improved guidance & example](https://trello.com/c/KfNxHLAk/1925-readme-improved-guidance-example)
