### ISSUE TITLE
Broken link in databricks support pages

### ISSUE THREAD

**Issue by chfoster** [dfe-analytical-services/analysts-guide#63]
**Describe the bug**
Would probably be changed with #57 anyway but wanted to note a couple of bugs/issues on the existing https://dfe-analytical-services.github.io/analysts-guide/ADA/databricks_rstudio_personal_cluster.html page. 

1. The hyperlink to databricks at the top of the page is broken/outdated. Needs updating, but would be good to investigate why this has changed (was it our fault/using a testing environment link, or will this happen again in future?)
2. the reference to 'step 5.e.ii' is incorrect and doesn't exist, needs updating. 

**To Reproduce**
1. Go to https://dfe-analytical-services.github.io/analysts-guide/ADA/databricks_rstudio_personal_cluster.html page. 
3. Click on the 'Databricks' hyperlink under step 2.ii
5. See error: 
<img width="544" alt="image" src="https://github.com/user-attachments/assets/dc07a355-2915-4871-a285-1bae2d0fb914">

**Expected behavior**
Link should take you to the log-in page for the databricks site.

**Comment by jen-machin** [comment]
I think this will be resolved by #57 so closing it 😄
