### ISSUE TITLE
Standardise use of info / warning / alert boxes

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/analysts-guide#71]
**Is your feature request related to a problem? Please describe.**
We're currently pretty inconsistent on these, e.g.
![image](https://github.com/user-attachments/assets/b5c50ae6-306b-4064-841b-a1ff02e56cbb)

versus

![image](https://github.com/user-attachments/assets/8b84ae50-aa73-4037-92c3-f43a63a88084)

**Describe the solution you'd like**
We should standardise all to one style, I'd personally back the inbuilt quarto ones using code like:

```
::: {.callout-note}
Text
:::
```

That look like this:
![image](https://github.com/user-attachments/assets/e52139f8-27c2-414c-87d5-f3c553e63cc7)

This should then be added to our [contributing style guide](https://github.com/dfe-analytical-services/analysts-guide/blob/main/CONTRIBUTING.md) to help new contributors know how to do them.

**Describe alternatives you've considered**
Not put much more thought into it behind this, I prefer the quarto inbuilt style to the ones I had added in the Open Data Standards page for example, so happy to move to the quarto approach.

**Additional context**
None.

**Comment by jen-machin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Analysts Guide: standardise use of callouts](https://trello.com/c/CYtvHhb3/1681-analysts-guide-standardise-use-of-callouts)
